'1':
  '1':
    collectd:
      - enabled: false
    continuous_queries:
      enabled: true
      log-enabled: true
      run-interval: 1s
    data:
      data-logging-enabled: true
      dir: /var/lib/influxdb/data
      enabled: true
      wal-dir: /var/lib/influxdb/wal
      wal-logging-enabled: true
    graphite:
      - enabled: false
    http:
      auth-enabled: false
      bind-address: :8086
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      max-row-limit: 10000
      pprof-enabled: false
      write-tracing: false
    meta:
      dir: /var/lib/influxdb/meta
      lease-duration: 1m0s
      logging-enabled: true
      pprof-enabled: false
      retention-autocreate: true
    monitor:
      store-database: _internal
      store-enabled: true
      store-interval: 10s
    opentsdb:
      - enabled: false
    reporting-disabled: false
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false     
'0':
  '13':
    admin:
      bind-address: :8083
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
    cluster:
      max-concurrent-queries: 0
      max-select-buckets: 0
      max-select-point: 0
      max-select-series: 0
      query-timeout: 0s
      shard-writer-timeout: 5s
      write-timeout: 10s
    collectd:
      - enabled: false
    continuous_queries:
      enabled: true
      log-enabled: true
    data:
      data-logging-enabled: true
      dir: /var/lib/influxdb/data
      enabled: true
      wal-dir: /var/lib/influxdb/wal
      wal-logging-enabled: true
    graphite:
      - enabled: false
    http:
      auth-enabled: false
      bind-address: :8086
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      max-row-limit: 10000
      pprof-enabled: false
      write-tracing: false
    meta:
      dir: /var/lib/influxdb/meta
      lease-duration: 1m0s
      logging-enabled: true
      pprof-enabled: false
      retention-autocreate: true
    monitor:
      store-database: _internal
      store-enabled: true
      store-interval: 10s
    opentsdb:
      - enabled: false
    reporting-disabled: false
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false
  '12':
    admin:
      bind-address: :8083
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
    cluster:
      shard-writer-timeout: 5s
      write-timeout: 10s
    collectd:
      enabled: false
    continuous_queries:
      enabled: true
      log-enabled: true
    data:
      data-logging-enabled: true
      dir: /var/lib/influxdb/data
      enabled: true
      wal-dir: /var/lib/influxdb/wal
      wal-logging-enabled: true
    graphite:
      - enabled: false
    hinted-handoff:
      dir: /var/lib/influxdb/hh
      enabled: true
      max-age: 168h
      max-size: 1073741824
      purge-interval: 1h
      retry-interval: 1s
      retry-max-interval: 1m
      retry-rate-limit: 0
    http:
      auth-enabled: false
      bind-address: :8086
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      pprof-enabled: false
      write-tracing: false
    meta:
      bind-address: :8088
      cluster-tracing: false
      commit-timeout: 50ms
      dir: /var/lib/influxdb/meta
      election-timeout: 1s
      enabled: true
      heartbeat-timeout: 1s
      http-bind-address: :8091
      https-certificate: ''
      https-enabled: false
      leader-lease-timeout: 500ms
      lease-duration: 1m0s
      logging-enabled: true
      pprof-enabled: false
      raft-promotion-enabled: true
      retention-autocreate: true
    monitor:
      store-database: _internal
      store-enabled: true
      store-interval: 10s
    opentsdb:
      enabled: false
    reporting-disabled: true
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false
  '11':
    admin:
      bind-address: :8083
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
    cluster:
      shard-writer-timeout: 5s
      write-timeout: 10s
    collectd:
      enabled: false
    continuous_queries:
      enabled: true
      log-enabled: true
    data:
      data-logging-enabled: true
      dir: /var/lib/influxdb/data
      enabled: true
      wal-dir: /var/lib/influxdb/wal
      wal-logging-enabled: true
    graphite:
      - enabled: false
    hinted-handoff:
      dir: /var/lib/influxdb/hh
      enabled: true
      max-age: 168h
      max-size: 1073741824
      purge-interval: 1h
      retry-interval: 1s
      retry-max-interval: 1m
      retry-rate-limit: 0
    http:
      auth-enabled: false
      bind-address: :8086
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      pprof-enabled: false
      write-tracing: false
    meta:
      bind-address: :8088
      cluster-tracing: false
      commit-timeout: 50ms
      dir: /var/lib/influxdb/meta
      election-timeout: 1s
      enabled: true
      heartbeat-timeout: 1s
      http-bind-address: :8091
      https-certificate: ''
      https-enabled: false
      leader-lease-timeout: 500ms
      lease-duration: 1m0s
      logging-enabled: true
      pprof-enabled: false
      raft-promotion-enabled: true
      retention-autocreate: true
    monitor:
      store-database: _internal
      store-enabled: true
      store-interval: 10s
    opentsdb:
      enabled: false
    reporting-disabled: true
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false
  '10':
    admin:
      bind-address: :8083
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
    cluster:
      shard-writer-timeout: 5s
      write-timeout: 10s
    collectd:
      enabled: false
    continuous_queries:
      enabled: true
      log-enabled: true
    data:
      data-logging-enabled: true
      dir: /var/lib/influxdb/data
      enabled: true
      max-wal-size: 104857600
      wal-dir: /var/lib/influxdb/wal
      wal-flush-interval: 10m
      wal-logging-enabled: true
      wal-partition-flush-delay: 2s
    graphite:
      - enabled: false
    hinted-handoff:
      dir: /var/lib/influxdb/hh
      enabled: true
      max-age: 168h
      max-size: 1073741824
      purge-interval: 1h
      retry-interval: 1s
      retry-max-interval: 1m
      retry-rate-limit: 0
    http:
      auth-enabled: false
      bind-address: :8086
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      pprof-enabled: false
      write-tracing: false
    meta:
      bind-address: :8088
      cluster-tracing: false
      commit-timeout: 50ms
      dir: /var/lib/influxdb/meta
      election-timeout: 1s
      enabled: true
      heartbeat-timeout: 1s
      leader-lease-timeout: 500ms
      retention-autocreate: true
    monitor:
      store-database: _internal
      store-enabled: true
      store-interval: 10s
    opentsdb:
      enabled: false
    reporting-disabled: true
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false
  '9':
    admin:
      bind-address: ':8083'
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
    cluster: {}
    collectd:
      enabled: false
    continuous_queries:
      compute-no-more-than: 2m
      compute-runs-per-interval: 10
      enabled: true
      log-enabled: true
      recompute-no-older-than: 10m
      recompute-previous-n: 2
    data:
      dir: /var/lib/influxdb/data
      wal-dir: /var/lib/influxdb/wal
      wal-logging-enabled: true
    graphite:
      - enabled: false
    hinted-handoff:
      dir: /var/lib/influxdb/hh
      enabled: true
      max-age: 168h
      max-size: 1073741824
      purge-interval: 1h
      retry-interval: 1s
      retry-max-interval: 1m
      retry-rate-limit: 0
    http:
      auth-enabled: false
      bind-address: ':8086'
      enabled: true
      https-certificate: /etc/ssl/influxdb.pem
      https-enabled: false
      log-enabled: true
      pprof-enabled: false
      write-tracing: false
    meta:
      bind-address: ':8088'
      cluster-tracing: false
      commit-timeout: 50ms
      dir: /var/lib/influxdb/meta
      election-timeout: 1s
      heartbeat-timeout: 1s
      hostname: localhost
      leader-lease-timeout: 500ms
      raft-promotion-enabled: true
      retention-autocreate: true
    monitor: {}
    opentsdb:
      enabled: false
    registration: {}
    reporting-disabled: true
    retention:
      check-interval: 30m
      enabled: true
    shard-precreation:
      advance-period: 30m
      check-interval: 10m
      enabled: true
    udp:
      - enabled: false
